/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hello3;

import java.util.*;
import java.sql.*;
import javax.swing.*;
import java.util.Date;
import java.util.Vector;
import java.awt.event.MouseEvent;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;

public class hello2 extends javax.swing.JFrame {

    String host = "jdbc:mysql://localhost:3306/hello1";
    String username = "root";
    String password = "Dhan@1234";
    Connection con;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int id, i, q;
    String gender;

    /**
     * Creates new form hello2
     */
    public hello2() {
        initComponents();
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void showData() {
        try {
            con = DriverManager.getConnection(host, username, password);
            pst = con.prepareStatement("select * from studentReg");
            rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            q = rsmd.getColumnCount();
            DefaultTableModel model = (DefaultTableModel) tab.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                Vector v = new Vector();
                for (i = 1; i <= q; i++) {
                    v.add(rs.getShort("id"));
                    v.add(rs.getString("studentName"));
                    v.add(rs.getString("fatherName"));
                    v.add(rs.getString("motherName"));
                    v.add(rs.getString("gender"));
                    v.add(rs.getString("Dob"));
                    v.add(rs.getString("email"));
                    v.add(rs.getString("department"));
                    v.add(rs.getString("mobileNo"));
                }
                model.addRow(v);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    public void cleardata() {
        TextStudentName.setText("");
        TextFatherName.setText("");
        TextMotherName.setText("");
        TextEmail.setText("");
        TextDate.setDate(null);
        TextMobileNo.setText("");
        //TextMale.isSelected(false);
    }

    public boolean validateForm() {
        String studentName = TextStudentName.getText();
        String fatherName = TextFatherName.getText();
        String motherName = TextMotherName.getText();
        String Gender = gender;
        try {
            SimpleDateFormat Dob = new SimpleDateFormat("yyyy-MM-dd");
            String d = Dob.format(TextDate.getDate());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            return false;
        }

        String email = TextEmail.getText();
        String department = TextDepartment.getSelectedItem().toString();
        String mobileNo = TextMobileNo.getText();
        if (studentName.equals("")) {
            JOptionPane.showMessageDialog(null, "please full fill up the form");
            return false;
        }
        if (fatherName.equals("")) {
            JOptionPane.showMessageDialog(null, "please full fill up the form");
            return false;
        }
        if (motherName.equals("")) {
            JOptionPane.showMessageDialog(null, "please full fill up the form");
            return false;
        }
        if (Gender.equals("")) {
            JOptionPane.showMessageDialog(null, "please full fill up the form");
            return false;
        }

        if (email.equals("")) {
            JOptionPane.showMessageDialog(null, "please full fill up the form");
            return false;
        }
        if (department.equals("")) {
            JOptionPane.showMessageDialog(null, "please full fill up the form");
            return false;
        }
        if (mobileNo.equals("")) {
            JOptionPane.showMessageDialog(null, "please full fill up the form");
            return false;
        }
        if (!TextAccepted.isSelected()) {
            JOptionPane.showMessageDialog(null, "please full fill up the form");
            return false;
        }
        return true;

    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextFatherName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextMotherName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextMale = new javax.swing.JRadioButton();
        TextFimale = new javax.swing.JRadioButton();
        TextOther = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        TextEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextDepartment = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        TextMobileNo = new javax.swing.JTextField();
        TextAccepted = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        TextSave = new javax.swing.JButton();
        TextDelete = new javax.swing.JButton();
        TextUpdate = new javax.swing.JButton();
        TextClear = new javax.swing.JButton();
        TextDate = new com.toedter.calendar.JDateChooser();
        TextStudentName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.pink);

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "NAME", "Father", "Mother", "Gender", "dob", "Email", "Department", "Mobile No"
            }
        ));
        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Student Name");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Father Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Mother Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Gender");

        buttonGroup1.add(TextMale);
        TextMale.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        TextMale.setForeground(new java.awt.Color(0, 0, 153));
        TextMale.setText("Male");
        TextMale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextMaleMouseClicked(evt);
            }
        });

        buttonGroup1.add(TextFimale);
        TextFimale.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        TextFimale.setForeground(new java.awt.Color(0, 0, 102));
        TextFimale.setText("Female");
        TextFimale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFimaleMouseClicked(evt);
            }
        });

        buttonGroup1.add(TextOther);
        TextOther.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        TextOther.setForeground(new java.awt.Color(0, 0, 153));
        TextOther.setText("Other");
        TextOther.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextOtherMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Date Of Birth");

        TextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEmailActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Email Id");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Department");

        TextDepartment.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        TextDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BCA", "MCA", "PG", "IA", "BA", "B.SC", "M.sc" }));
        TextDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDepartmentActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Mobile No");

        TextAccepted.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        TextAccepted.setForeground(new java.awt.Color(0, 0, 153));
        TextAccepted.setText("i Accepted All Term And Conditions For Fill The Form.......");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("Student Registration");

        TextSave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TextSave.setForeground(new java.awt.Color(255, 51, 0));
        TextSave.setText("Save");
        TextSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TextSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextSaveMouseClicked(evt);
            }
        });
        TextSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextSaveActionPerformed(evt);
            }
        });

        TextDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TextDelete.setForeground(new java.awt.Color(255, 51, 0));
        TextDelete.setText("Delete");
        TextDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TextDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDeleteActionPerformed(evt);
            }
        });

        TextUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TextUpdate.setForeground(new java.awt.Color(255, 51, 51));
        TextUpdate.setText("Update");
        TextUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TextUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextUpdateMouseClicked(evt);
            }
        });

        TextClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TextClear.setForeground(new java.awt.Color(255, 51, 51));
        TextClear.setText("Clear");
        TextClear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TextClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextClearMouseClicked(evt);
            }
        });
        TextClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextClearActionPerformed(evt);
            }
        });

        TextStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextStudentNameActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Show");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TextMale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TextFimale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TextOther, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(TextDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TextMobileNo, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(TextDepartment, javax.swing.GroupLayout.Alignment.LEADING, 0, 240, Short.MAX_VALUE)
                                                .addComponent(TextEmail, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(TextStudentName, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(TextFatherName, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(TextMotherName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))))
                                    .addComponent(TextSave, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextDelete)
                                .addGap(26, 26, 26)
                                .addComponent(TextUpdate)
                                .addGap(37, 37, 37)
                                .addComponent(TextClear)
                                .addGap(41, 41, 41)
                                .addComponent(jButton1))
                            .addComponent(TextAccepted, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(TextStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(TextFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(TextMotherName, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TextMale)
                            .addComponent(TextFimale)
                            .addComponent(TextOther))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(TextEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(TextDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(TextMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(TextAccepted, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextSave)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TextClear)
                                .addComponent(jButton1)
                                .addComponent(TextUpdate)
                                .addComponent(TextDelete)))
                        .addGap(77, 77, 77))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDepartmentActionPerformed

    private void TextStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextStudentNameActionPerformed

    private void TextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEmailActionPerformed

    private void TextMaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextMaleMouseClicked
        gender = TextMale.getText();
    }//GEN-LAST:event_TextMaleMouseClicked

    private void TextFimaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFimaleMouseClicked
        gender = TextFimale.getText();
    }//GEN-LAST:event_TextFimaleMouseClicked

    private void TextOtherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextOtherMouseClicked
        gender = TextOther.getText();
    }//GEN-LAST:event_TextOtherMouseClicked

    private void TextSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextSaveMouseClicked
       
    }//GEN-LAST:event_TextSaveMouseClicked

    private void tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseClicked
        DefaultTableModel model = (DefaultTableModel) tab.getModel();
        int sr = tab.getSelectedRow();
        try {

            TextStudentName.setText(model.getValueAt(sr, 1).toString());
            TextFatherName.setText(model.getValueAt(sr, 2).toString());
            TextMotherName.setText(model.getValueAt(sr, 3).toString());
            String gen = model.getValueAt(sr, 4).toString();
            gender = gen;
            switch (gen) {
                case "Male":
                    TextMale.setSelected(true);
                    break;
                case "Female":
                    TextFimale.setSelected(true);
                    break;
                case "TextOther":
                    TextMale.setSelected(true);
                    break;
                default:
                    break;
            }
            Date d = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            d = sdf.parse(model.getValueAt(sr, 5).toString());
            TextDate.setDate(d);
            TextEmail.setText(model.getValueAt(sr, 6).toString());
            TextDepartment.setSelectedItem(model.getValueAt(sr, 7).toString());
            TextMobileNo.setText(model.getValueAt(sr, 8).toString());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_tabMouseClicked

    private void TextUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextUpdateMouseClicked
        DefaultTableModel model = (DefaultTableModel) tab.getModel();
        int sr = tab.getSelectedRow();
        try {
            id = Integer.parseInt(model.getValueAt(sr, 0).toString());
            con = DriverManager.getConnection(host, username, password);
            Date d = TextDate.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String Date = sdf.format(d);
            pst = con.prepareStatement("update studentReg  set studentName = ?,fatherName=?,motherName=?,gender=?,Dob=?,email=?,department=?,MobileNo=? where id=?");

            pst.setString(1, TextStudentName.getText());
            pst.setString(2, TextFatherName.getText());
            pst.setString(3, TextMotherName.getText());
            pst.setString(4, gender);
            pst.setString(5, Date);
            pst.setString(6, TextEmail.getText());
            pst.setString(7, TextDepartment.getSelectedItem().toString());
            pst.setString(8, TextMobileNo.getText());
            pst.setInt(9, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Update Record Succesfully");
//            showData();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
// TODO add your handling code here:
    }//GEN-LAST:event_TextUpdateMouseClicked

    private void TextDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) tab.getModel();
        int sr = tab.getSelectedRow();
        try {
            id = Integer.parseInt(model.getValueAt(sr, 0).toString());
            con = DriverManager.getConnection(host, username, password);
            pst = con.prepareStatement("Delete from studentReg where id=?");
            pst.setInt(1, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Delete Record Succesfully");
            cleardata();
            showData();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error" + ex);

        }
// TODO add your handling code here:
    }//GEN-LAST:event_TextDeleteActionPerformed

    private void TextClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextClearMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_TextClearMouseClicked

    private void TextClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextClearActionPerformed
        cleardata();
        // TODO add your handling code here:
    }//GEN-LAST:event_TextClearActionPerformed

    private void TextSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextSaveActionPerformed
        if (validateForm() == true) {
            try {
                con = DriverManager.getConnection(host, username, password);
                Date d = TextDate.getDate();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String dob = sdf.format(d);
                pst = con.prepareStatement("insert into StudentReg(studentName,fatherName,motherName,gender,Dob,email,department,mobileNo) values(?,?,?,?,?,?,?,?)");
                pst.setString(1, TextStudentName.getText());
                pst.setString(2, TextFatherName.getText());
                pst.setString(3, TextMotherName.getText());
                pst.setString(4, gender);
                pst.setString(5, dob);
                pst.setString(6, TextEmail.getText());
                pst.setString(7, TextDepartment.getSelectedItem().toString());

                pst.setString(8, TextMobileNo.getText());

                pst.executeUpdate();
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());

            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hello2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hello2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hello2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hello2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hello2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox TextAccepted;
    private javax.swing.JButton TextClear;
    private com.toedter.calendar.JDateChooser TextDate;
    private javax.swing.JButton TextDelete;
    private javax.swing.JComboBox<String> TextDepartment;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JTextField TextFatherName;
    private javax.swing.JRadioButton TextFimale;
    private javax.swing.JRadioButton TextMale;
    private javax.swing.JTextField TextMobileNo;
    private javax.swing.JTextField TextMotherName;
    private javax.swing.JRadioButton TextOther;
    private javax.swing.JButton TextSave;
    private javax.swing.JTextField TextStudentName;
    private javax.swing.JButton TextUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab;
    // End of variables declaration//GEN-END:variables
}
